'use strict';
const $=id=>document.getElementById(id);const {W,H,G,COLORS,starter,clone,validate,Game}=Trail;
let languageStorage;try{languageStorage=localStorage;}catch{languageStorage={getItem(){return null;},setItem(){}};}
const locale=TrailI18n.create(languageStorage,typeof navigator==='undefined'?'en':navigator.language);
const tr=source=>locale.t(source),liveTexts=new Map();
function setText(element,source,translate=true){liveTexts.set(element,{source,translate});element.textContent=translate?tr(source):source;}
function displayName(l){const original=BUILTINS.find(b=>b.id===l.id);return original&&original.name===l.name?tr(l.name):(l.name||tr('Your color trail'));}
function applyLanguage(){
 document.documentElement.lang=locale.language==='zh'?'zh-CN':'en';document.title=tr('Step by Step — A little platform adventure');
 document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=tr(el.getAttribute('data-i18n'));});
 for(const attr of ['aria-label','title','placeholder'])document.querySelectorAll('[data-i18n-'+attr+']').forEach(el=>el.setAttribute(attr,tr(el.getAttribute('data-i18n-'+attr))));
 for(const [el,value]of liveTexts){if(el.isConnected===false){liveTexts.delete(el);continue;}el.textContent=value.translate?tr(value.source):value.source;}
 $('languageToggle').textContent=locale.language==='zh'?'中文 · EN':'中文 / EN';$('languageToggle').setAttribute('aria-label',locale.language==='zh'?'Switch to English':'切换为中文');$('languageToggle').setAttribute('title',locale.language==='zh'?'Switch to English':'切换为中文');
 title();updateProgress();palette();check();if(!$('levelLibrary').hidden)renderLibrary();if(!$('overlay').hidden){if(game.won)showWin();else showOverlay('TAKE A BREATHER','A moment between jumps.','Your trail will be right here.','Keep going ▶');}
}
$('languageToggle').onclick=()=>{locale.setLanguage(locale.language==='zh'?'en':'zh');applyLanguage();};
function nextLevelSource(){const i=BUILTINS.findIndex(l=>l.id===activeId);if(i>=0)return BUILTINS[i+1]||null;const j=store.levels.findIndex(l=>l.id===activeId);return j>=0?store.levels[j+1]||null:null;}
function showWin(){const next=nextLevelSource();const message=next?'Continue to “'+displayName(next)+'”?':activeId?.startsWith('builtin-')?'Final built-in level complete. Choose any other trail or replay this one.':activeId?'Last custom level complete. Pick another trail or make a new one.':'Playtest complete. Replay or return to the editor to keep building.';showOverlay('RAINBOW COMPLETE','Every color. One big win.',message,'Play again ↗');}
$('nextLevel').onclick=()=>{if(!game.won)return;const next=nextLevelSource();if(next)selectLevel(next);};
const BUILTINS=TrailLevels.builtins();
let store;try{store=new TrailLevels.LevelStore(localStorage);}catch{store=new TrailLevels.LevelStore({getItem(){return null;},setItem(){throw Error('Storage unavailable');}});}
const canvas=$('game'),ctx=canvas.getContext('2d'),fxCtx=$('victoryFx').getContext('2d');
let level=clone(BUILTINS[0]),activeId=level.id,editingSavedId=null,draft=null,custom=false,mode='play',paused=false,run=1,tool='select',selected=null,hover=null,keys={},jump=false,history=[],future=[],clock=0,particles=[],messageAt=0,celebration=null;
try{const saved=JSON.parse(localStorage.getItem('step-by-step-draft'));if(saved&&Array.isArray(saved.blocks)&&Array.isArray(saved.spikes)&&!validate({...saved,blocks:[...saved.blocks.filter(b=>!b.n),...starter().blocks.filter(b=>b.n)]}).length)draft=saved;}catch{}
function title(){ setText($('levelTitle'),displayName(level),false);const i=BUILTINS.findIndex(l=>l.id===activeId);setText($('levelSubtitle'),mode==='edit'?'YOUR MEADOW · YOUR RULES':i>=0?`LEVEL ${String(i+1).padStart(2,'0')} · ${BUILTINS[i].difficulty.toUpperCase()}`:activeId?'CUSTOM LEVEL':'EDITOR PLAYTEST');}
function preserveDraft(){if(mode==='edit'||!activeId){draft=clone(level);try{localStorage.setItem('step-by-step-draft',JSON.stringify(draft));}catch{}}}
function selectLevel(source){preserveDraft();level=clone(source);activeId=source.id;editingSavedId=source.id.startsWith('custom-')?source.id:null;custom=!!editingSavedId;history=[];future=[];selected=null;run=1;closeLibrary();setMode('play');title();}
function openLibrary(){preserveDraft();keys={};jump=false;if(mode==='play')paused=true;renderLibrary();$('levelLibrary').hidden=false;$('chooseLevels').setAttribute('aria-expanded','true');$('levelLibrary').scrollIntoView({behavior:'auto',block:'start'});$('closeLibrary').focus({preventScroll:true});}
function closeLibrary(){ $('levelLibrary').hidden=true;$('chooseLevels').setAttribute('aria-expanded','false');if($('overlay').hidden)paused=false;}
function miniLevel(l){const c=document.createElement('canvas');c.width=288;c.height=128;c.setAttribute('aria-hidden','true');const x=c.getContext('2d');x.scale(.2,.2);x.fillStyle='#e9f3f3';x.fillRect(0,0,W,H);for(const b of l.blocks){x.fillStyle=b.n?COLORS[b.n-1].fill:'#88aa96';x.fillRect(b.x,b.y,b.w,b.h);}x.fillStyle='#657e80';for(const b of l.spikes){for(let px=b.x;px<b.x+b.w;px+=20){x.beginPath();x.moveTo(px,b.y+b.h);x.lineTo(px+10,b.y);x.lineTo(px+20,b.y+b.h);x.fill();}}x.fillStyle='#e7794d';x.fillRect(l.spawn.x,l.spawn.y,28,36);x.fillStyle='#237c70';x.fillRect(l.flag.x,l.flag.y-70,4,110);x.fillRect(l.flag.x,l.flag.y-70,38,23);return c;}
function renderLibrary(){for(const [id,items]of [['builtinLevels',BUILTINS],['customLevels',store.levels]]){const list=$(id);list.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='library-empty';setText(p,'No extra levels yet. Open the editor, build a trail, and save it here.');list.append(p);}items.forEach((l,i)=>{const b=document.createElement('button');b.className='level-card';b.setAttribute('aria-label',`${id==='builtinLevels'?(locale.language==='zh'?'第 '+(i+1)+' 关：':'Level '+(i+1)+': '):''}${displayName(l)}. ${tr(l.difficulty)}. ${store.completed.includes(l.id)?tr('Completed. '):''}${tr('Play level')}`);b.setAttribute('aria-pressed',l.id===activeId);b.append(miniLevel(l));const meta=document.createElement('span');meta.className='level-meta';setText(meta,(id==='builtinLevels'?String(i+1).padStart(2,'0')+' · ':'')+tr(l.difficulty)+(store.completed.includes(l.id)?(locale.language==='zh'?' · ✓ 已通关':' · ✓ Complete'):''));const name=document.createElement('strong');setText(name,displayName(l),false);const desc=document.createElement('span');desc.className='level-description';setText(desc,l.description);b.append(meta,name,desc);b.onclick=()=>selectLevel(l);list.append(b);});}setText($('completionCount'),BUILTINS.filter(l=>store.completed.includes(l.id)).length+' / 10 complete');}
function saveExtra(update){if(!check()){setText($('saveLevelFeedback'),'Add every color before saving this level.');return;}try{const saved=store.save(level,$('levelName').value,update?editingSavedId:null);level=saved;activeId=saved.id;editingSavedId=saved.id;custom=true;draft=clone(level);save();$('levelName').setAttribute('aria-invalid','false');setText($('saveLevelFeedback'),'Saved “'+saved.name+'” to your extra levels.');$('updateLevel').disabled=false;renderLibrary();setText($('libraryStatus'),'Saved “'+saved.name+'”. Select its card to play anytime.');openLibrary();}catch(error){setText($('saveLevelFeedback'),error.message.includes('name')?error.message:'Could not save the level. Your draft is still here; export a backup.');if(error.message.includes('name')){$('levelName').setAttribute('aria-invalid','true');$('levelName').focus();}}}
$('chooseLevels').onclick=()=> $('levelLibrary').hidden?openLibrary():closeLibrary();$('closeLibrary').onclick=()=>{closeLibrary();$('chooseLevels').focus();};$('winLevels').onclick=openLibrary;
$('saveAsLevel').onclick=()=>saveExtra(false);$('updateLevel').onclick=()=>saveExtra(true);
$('levelName').addEventListener('input',()=>{level.name=$('levelName').value;save();});
$('resumeDraft').onclick=()=>{if(draft){level=clone(draft);editingSavedId=store.levels.some(l=>l.id===draft.id)?draft.id:null;}else{level=clone(BUILTINS[0]);editingSavedId=null;}activeId=null;history=[];future=[];selected=null;closeLibrary();setMode('edit');};
setText($('libraryStatus'),store.error);

function say(text){setText($('status'),text);messageAt=clock;}
const melody=TrailAudio.create({makeContext:()=>new (window.AudioContext||window.webkitAudioContext)()});
try{if(localStorage.getItem('step-by-step-sound')==='off')melody.setEnabled(false);}catch{}
function soundLabel(){setText($('sound'),!melody.enabled?'♪ Sound off':melody.failed?'♪ Retry sound':melody.ready?'♪ Sound on':'♪ Enable sound');$('sound').setAttribute('aria-pressed',melody.enabled&&melody.ready);}
function unlockSound(){void melody.unlock().then(soundLabel);}
window.addEventListener('pointerdown',e=>{if(e.target===canvas||e.target.closest?.('[data-key]'))unlockSound();});
window.addEventListener('click',e=>{if(!e.target.closest?.('#sound'))unlockSound();});
window.addEventListener('keydown',e=>{if(e.isComposing||e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA'||e.target.closest?.('#sound'))return;unlockSound();});
soundLabel();

function event(type,n,expected){if(type==='reset'&&mode==='play')melody.start();if(type==='color'){say(n===6?'All six colors! Head for the flag.':`${COLORS[n-1].name} collected. Next stop: ${COLORS[n].name.toLowerCase()}.`);melody.note(n);if(game)for(let i=0;i<15;i++)particles.push({x:game.p.x+13,y:game.p.y+30,vx:(Math.random()-.5)*150,vy:-Math.random()*150,life:.6,color:COLORS[n-1].fill});}if(type==='order'){say(`That was ${COLORS[n-1].name.toLowerCase()}. Expected ${COLORS[(expected||1)-1]?.name.toLowerCase()||'the flag'}. All colors cleared — start with red.`);melody.start();}if(type==='death'){run++;say('Ouch! Fresh start. Find the red block.');}if(type==='locked'&&clock-messageAt>3)say('The flag needs all six colors. Keep going!');if(type==='win'){say('Trail complete. Beautifully done.');melody.note(7);celebration=TrailVictory.create(level.flag.x+12,level.flag.y-45,window.matchMedia('(prefers-reduced-motion: reduce)').matches);try{store.complete(activeId);}catch{setText($('libraryStatus'),'Level complete! Progress could not be saved on this device.');}}updateProgress();}
let game;game=new Game(level,event);
function updateProgress(){if(!game)return;const progress=mode==='edit'?0:game.progress;$('sequence').innerHTML=COLORS.map((color,i)=>`<span class="color-step ${i<progress?'done':i===progress?'next':''}" style="--swatch:${color.fill};--swatch-edge:${color.edge};--swatch-ink:${color.ink}" title="${tr(color.name)}: ${tr(i<progress?'complete':i===progress?'next':'remaining')}" aria-label="${tr(color.name)}: ${tr(i<progress?'complete':i===progress?'next':'remaining')}">${i<progress?'✓':tr(color.name)}</span>`).join('');setText($('attempt'),'RUN '+String(run).padStart(2,'0'));}
function showOverlay(eyebrow,title,text,button){setText($('overlayEyebrow'),eyebrow);setText($('overlayTitle'),title);setText($('overlayText'),text);setText($('resume'),button);$('overlay').hidden=false;$('overlay').classList.toggle('victory',!!game.won);$('winLevels').hidden=!game.won;$('nextLevel').hidden=!game.won||!nextLevelSource();$('resume').classList.toggle('primary',$('nextLevel').hidden);setText($('nextLevel'),'Next level →');}
function restart(){celebration=null;particles=[];jump=false;paused=false;$('overlay').hidden=true;keys={};game=new Game(level,event);updateProgress();say(activeId?.startsWith('builtin-')&&level.lesson?level.lesson:'Start with red. You’ve got this.');canvas.focus({preventScroll:true});}
function setMode(next){closeLibrary();celebration=null;if(next==='edit'){melody.silence();setText($('saveLevelFeedback'),'Save a playable copy to your level library.');if(activeId){editingSavedId=activeId.startsWith('custom-')?activeId:null;}activeId=null;$('levelName').value=level.name||'My color trail';$('updateLevel').disabled=!editingSavedId;$('undo').disabled=!history.length;$('redo').disabled=!future.length;}mode=next;paused=false;keys={};$('overlay').hidden=true;$('editor').hidden=next!=='edit';$('editorBadge').hidden=next!=='edit';$('playMode').classList.toggle('active',next==='play');$('editMode').classList.toggle('active',next==='edit');$('playMode').setAttribute('aria-pressed',next==='play');$('editMode').setAttribute('aria-pressed',next==='edit');$('pause').disabled=next==='edit';$('restart').disabled=next==='edit';title();setText($('stageHint'),next==='edit'?'ARROWS TO POSITION · ENTER TO PLACE':'SIX COLORS. ONE WAY FORWARD.');if(next==='play')restart();else{say('Choose a piece below, then click to place.');check();updateProgress();}canvas.focus({preventScroll:true});}
function check(){const errors=validate(level);setText($('validation'),errors.length?errors.map(tr).join(' '):'All six colors are in place. Ready to test. Reachability is yours to explore.');return errors.length===0;}
function play(){if(check())setMode('play');else{setMode('edit');say('Add the missing color blocks before testing.');}}
$('playMode').onclick=play;$('editMode').onclick=()=>setMode('edit');$('testLevel').onclick=play;$('restart').onclick=()=>{run++;restart();};
function pause(){if(mode!=='play'||game.won)return;paused=!paused;keys={};if(paused)showOverlay('TAKE A BREATHER','A moment between jumps.','Your trail will be right here.','Keep going ▶');else{$('overlay').hidden=true;canvas.focus({preventScroll:true});}}
$('pause').onclick=pause;$('resume').onclick=()=>{if(game.won){run++;restart();}else pause();};$('sound').onclick=()=>{if(melody.enabled&&!melody.ready){unlockSound();return;}melody.setEnabled(!melody.enabled);try{localStorage.setItem('step-by-step-sound',melody.enabled?'on':'off');}catch{}if(melody.enabled){if(mode==='play')melody.note(game.won?7:game.progress);unlockSound();}soundLabel();};
function save(){draft=clone(level);activeId=null;try{localStorage.setItem('step-by-step-draft',JSON.stringify(level));setText($('saveStatus'),'Draft saved on this device');}catch{setText($('saveStatus'),'Storage unavailable. Export to keep your level.');}check();$('undo').disabled=!history.length;$('redo').disabled=!future.length;custom=true;title();}
function commit(fn){history.push(clone(level));if(history.length>100)history.shift();future=[];fn();save();}
$('undo').onclick=()=>{if(!history.length)return;future.push(clone(level));level=history.pop();$('levelName').value=level.name||'';selected=null;save();};$('redo').onclick=()=>{if(!future.length)return;history.push(clone(level));level=future.pop();$('levelName').value=level.name||'';selected=null;save();};
const tools=[['select','↖ Select'],['plain','■ Block'],...COLORS.map((color,i)=>['n'+(i+1),color.name]),['spike','△ Spike'],['spawn','☺ Start'],['flag','⚑ Flag'],['erase','⌫ Erase']];
function palette(){ $('palette').innerHTML='';for(const [id,label]of tools){const b=document.createElement('button');setText(b,label);b.className=id===tool?'selected':'';b.setAttribute('aria-pressed',id===tool);b.setAttribute('aria-label',tr(id.startsWith('n')?label+' block':label));if(id.startsWith('n')){const swatch=document.createElement('span');swatch.className='palette-swatch';swatch.style.background=COLORS[Number(id.slice(1))-1].fill;swatch.setAttribute('aria-hidden','true');b.prepend(swatch);}b.onclick=()=>{tool=id;selected=null;palette();say(id==='select'?'Click a piece, then click its new position.':'Click the meadow to place '+label.replace(/^[^\w]+/,'')+'.');};$('palette').append(b);}}
function hit(x,y){if(x>=level.spawn.x&&x<level.spawn.x+40&&y>=level.spawn.y&&y<level.spawn.y+40)return {kind:'spawn'};if(x>=level.flag.x&&x<level.flag.x+40&&y>=level.flag.y-80&&y<level.flag.y+40)return{kind:'flag'};for(const kind of ['spikes','blocks'])for(let i=level[kind].length-1;i>=0;i--){const b=level[kind][i];if(x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h)return{kind,i};}return null;}
function place(x,y){if(mode!=='edit')return;const item=hit(x+10,y+10);if(tool==='select'){if(selected){const s=selected;commit(()=>{const b=s.i===undefined?level[s.kind]:level[s.kind][s.i];b.x=Math.min(x,W-(b.w||40));b.y=Math.min(y,H-(b.h||40));});selected=null;say('Piece moved. Undo is available.');}else{selected=item;say(item?'Piece selected. Click its new position.':'Click a piece to select it.');}return;}if(tool==='erase'){if(item&&item.i!==undefined)commit(()=>level[item.kind].splice(item.i,1));else say('Start and flag can be moved, but not erased.');return;}commit(()=>{if(tool==='spawn'||tool==='flag')level[tool]={x,y};else if(tool==='spike')level.spikes.push({x,y,w:40,h:40});else{const n=tool.startsWith('n')?Number(tool.slice(1)):0;if(n)level.blocks=level.blocks.filter(b=>b.n!==n);level.blocks.push({x:Math.min(x,W-(n?80:40)),y,w:n?80:40,h:40,n});}});}
function cursor(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(W-40,Math.floor((e.clientX-r.left)/r.width*W/G)*G)),y:Math.max(0,Math.min(H-40,Math.floor((e.clientY-r.top)/r.height*H/G)*G))};}
canvas.addEventListener('pointermove',e=>{hover=cursor(e);});canvas.addEventListener('pointerleave',()=>{hover=null;});canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});hover=cursor(e);place(hover.x,hover.y);});
$('clearLevel').onclick=()=>{commit(()=>{level={name:'My color trail',spawn:{x:80,y:520},flag:{x:1360,y:520},blocks:[],spikes:[]};});$('levelName').value=level.name;selected=null;say('Blank meadow. Place ground and all six colors. Undo restores your level.');};$('resetLevel').onclick=()=>{commit(()=>{level=starter();});$('levelName').value=level.name;selected=null;say('Starter restored. Undo brings back your previous level.');};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(level,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='color-trail.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Level exported. Import it here to keep building.');};$('import').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>200000)throw Error('File is too large. Choose a level under 200 KB.');const incoming=JSON.parse(await file.text()),errors=validate(incoming);if(errors.length)throw Error(errors.map(tr).join(' '));commit(()=>{level=clone(incoming);});$('levelName').value=level.name||'Imported trail';editingSavedId=null;$('updateLevel').disabled=true;selected=null;say('Level imported and saved. Ready to test.');}catch(error){setText($('validation'),error instanceof SyntaxError?'Could not read this file. Choose an exported JSON level.':error.message);say('Import failed. Your current level is safe.');}e.target.value='';};
const controls=['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW'];window.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;if(!$('levelLibrary').hidden){if(e.code==='Escape'){closeLibrary();$('chooseLevels').focus();}return;}if(mode==='edit'&&document.activeElement===canvas){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','Delete','Backspace','Escape'].includes(e.code)){e.preventDefault();hover ||= {x:80,y:400};if(e.code==='Escape')selected=null;if(e.code==='ArrowLeft')hover.x=Math.max(0,hover.x-G);if(e.code==='ArrowRight')hover.x=Math.min(W-G,hover.x+G);if(e.code==='ArrowUp')hover.y=Math.max(0,hover.y-G);if(e.code==='ArrowDown')hover.y=Math.min(H-G,hover.y+G);if(e.code==='Enter')place(hover.x,hover.y);if(e.code==='Delete'||e.code==='Backspace'){const prev=tool;tool='erase';place(hover.x,hover.y);tool=prev;}}return;}if(mode!=='play'||(document.activeElement.tagName==='BUTTON'&&e.code==='Space'))return;if(controls.includes(e.code)){e.preventDefault();if(!keys[e.code]&&['Space','ArrowUp','KeyW'].includes(e.code))jump=true;keys[e.code]=true;}if(e.code==='KeyR'&&!e.repeat){run++;restart();}if(e.code==='KeyP'&&!e.repeat)pause();});window.addEventListener('keyup',e=>{keys[e.code]=false;});window.addEventListener('blur',()=>{keys={};jump=false;if(mode==='play'&&!paused&&!game.won)pause();});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;if(b.dataset.key==='Space')jump=true;};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys[b.dataset.key]=false);});
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function round(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}function line(x,y,x2,y2,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}function text(t,x,y,size,color,font='monospace'){ctx.fillStyle=color;ctx.font=`bold ${size}px ${font}`;ctx.textAlign='center';ctx.fillText(t,x,y);}
function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);round(-45,0,130,23,12,'#ffffffb0');circle(-5,-5,28,'#ffffffb0');circle(30,-10,35,'#ffffffb0');ctx.restore();}
function hills(){ctx.fillStyle='#d3e7df';ctx.beginPath();ctx.moveTo(0,560);ctx.lineTo(0,426);ctx.bezierCurveTo(180,210,280,325,440,430);ctx.bezierCurveTo(680,185,790,300,990,448);ctx.bezierCurveTo(1190,240,1340,288,1440,404);ctx.lineTo(1440,640);ctx.lineTo(0,640);ctx.fill();ctx.fillStyle='#b8d4c4';ctx.beginPath();ctx.moveTo(0,570);ctx.bezierCurveTo(230,390,380,475,580,530);ctx.bezierCurveTo(900,340,1080,500,1230,500);ctx.bezierCurveTo(1340,425,1380,450,1440,500);ctx.lineTo(1440,640);ctx.lineTo(0,640);ctx.fill();}
function block(b){if(b.n){const color=COLORS[b.n-1],done=mode==='play'&&b.n<=game.progress;round(b.x,b.y+4,b.w,b.h,5,color.edge);round(b.x,b.y,b.w,b.h-4,5,color.fill);rect(b.x+5,b.y+4,b.w-10,3,color.shine);circle(b.x+7,b.y+10,2,color.edge);circle(b.x+b.w-7,b.y+10,2,color.edge);text(tr(color.name),b.x+b.w/2,b.y+26,Math.min(14,b.w/4.5),color.ink);if(done){circle(b.x+b.w-4,b.y-2,10,'#fffef7');text('✓',b.x+b.w-4,b.y+3,14,'#237c70');}}else{rect(b.x,b.y,b.w,b.h,'#739c88');rect(b.x,b.y,b.w,9,'#acc791');rect(b.x,b.y+9,b.w,5,'#477d6a');for(let x=b.x;x<b.x+b.w;x+=40){rect(x+3,b.y+21,7,4,'#8eb29a');rect(x+26,b.y+31,5,4,'#618a77');}if(b.h>40){for(let y=b.y+44;y<b.y+b.h;y+=24)for(let x=b.x+15;x<b.x+b.w;x+=50)rect(x,y,9,4,'#608a78');}}}
function player(x,y,ghost=false){ctx.save();ctx.globalAlpha=ghost?.6:1;const bob=mode==='play'&&game.p.ground&&game.p.vx?Math.sin(clock*20)*2:0;rect(x+3,y+27,8,9,'#294951');rect(x+17,y+27,8,9,'#294951');round(x,y+11+bob,26,20,4,'#e7794d');rect(x+6,y+13+bob,16,10,'#ffdab0');rect(x+17,y+15+bob,3,4,'#294951');round(x-2,y+2+bob,30,13,4,'#dc6542');rect(x+20,y+10+bob,13,5,'#c45c3d');rect(x-4,y+20+bob,7,8,'#ffdab0');rect(x+24,y+20+bob,6,8,'#ffdab0');ctx.restore();}
function flag(){const f=level.flag,unlocked=game.progress===6&&mode==='play';rect(f.x+8,f.y-74,5,114,'#6c8374');circle(f.x+10,f.y-78,5,'#e5b45b');ctx.fillStyle=unlocked?'#e98850':'#487d70';ctx.beginPath();ctx.moveTo(f.x+13,f.y-72);ctx.lineTo(f.x+58,f.y-65);ctx.lineTo(f.x+49,f.y-48);ctx.lineTo(f.x+13,f.y-49);ctx.fill();rect(f.x-1,f.y+35,24,5,'#698d74');text(unlocked?tr('GO!'):'⚑',f.x+34,f.y-55,14,'#fff9d9');}
function draw(){rect(0,0,W,H,'#e9f3f3');circle(1200,106,45,'#f5de9d');circle(1200,106,57,'#f5de9d25');cloud(150,130,.9);cloud(510,90,.75);cloud(910,161,.95);cloud(1345,210,.55);hills();for(const [x,y]of [[110,531],[290,518],[490,541],[860,519],[1150,529],[1285,540]]){line(x,y,x,y-18,'#7b9d78',3);line(x,y-6,x-7,y-13,'#7b9d78',3);circle(x,y-20,5,'#f2df9b');}if(mode==='edit'){ctx.strokeStyle='#517f751e';ctx.lineWidth=1;for(let x=0;x<=W;x+=G){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<=H;y+=G){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}}
for(const b of level.blocks)block(b);for(const s of level.spikes){rect(s.x,s.y+s.h-6,s.w,6,'#758b89');for(let x=s.x;x<s.x+s.w;x+=20){ctx.fillStyle='#edf3eb';ctx.strokeStyle='#728d89';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+1,s.y+s.h-6);ctx.lineTo(x+10,s.y+5);ctx.lineTo(Math.min(x+19,s.x+s.w),s.y+s.h-6);ctx.closePath();ctx.fill();ctx.stroke();}}flag();if(mode==='play')player(game.p.x,game.p.y);else{player(level.spawn.x+7,level.spawn.y+4,true);text(tr('START'),level.spawn.x+20,level.spawn.y-8,12,'#477c70');}
if(mode==='play'&&game.progress<6){const next=level.blocks.find(b=>b.n===game.progress+1);if(next){const dy=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.sin(clock*3)*3;text('↓',next.x+next.w/2,next.y-18+dy,24,'#628576');}}
if(mode==='edit'&&hover){const w=tool.startsWith('n')?80:40;ctx.fillStyle='#ffffff60';ctx.fillRect(hover.x,hover.y,w,40);ctx.strokeStyle='#276b60';ctx.lineWidth=2;ctx.strokeRect(hover.x+1,hover.y+1,w-2,38);}if(mode==='edit'&&selected){const b=selected.i===undefined?level[selected.kind]:level[selected.kind][selected.i];if(b){ctx.strokeStyle='#d56b37';ctx.lineWidth=3;ctx.strokeRect(b.x-2,b.y-2,(b.w||40)+4,(b.h||40)+4);}}
for(const p of particles)rect(p.x,p.y,5,5,p.color);}
let prev=0,acc=0;function frame(time){let dt=Math.min((time-prev)/1000,.05);prev=time;clock+=dt;if(mode==='play'&&!paused){acc+=dt;while(acc>=1/120){game.step(1/120,{left:keys.ArrowLeft||keys.KeyA,right:keys.ArrowRight||keys.KeyD,jump});jump=false;acc-=1/120;}}else{acc=0;jump=false;}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=350*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);draw();TrailVictory.draw(fxCtx,celebration,dt);if(celebration&&game.won&&$('overlay').hidden&&celebration.age>(celebration.reduced?.1:1.25))showWin();requestAnimationFrame(frame);}palette();updateProgress();title();if(validate(level).length)setMode('edit');applyLanguage();if(mode==='play'&&level.lesson)say(level.lesson);requestAnimationFrame(frame);
