const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
function boot(storage={data:{},getItem(k){return this.data[k]||null},setItem(k,v){this.data[k]=v}}){
 const elements={};const paint=new Proxy({},{get:(t,k)=>t[k]||(()=>{}),set:(t,k,v)=>(t[k]=v,true)});
 function element(tag='div'){return {tagName:tag.toUpperCase(),hidden:false,value:'',textContent:'',innerHTML:'',children:[],style:{},attributes:{},classList:{toggle(){}},setAttribute(k,v){this.attributes[k]=v},append(...items){this.children.push(...items)},prepend(item){this.children.unshift(item)},replaceChildren(){this.children=[]},addEventListener(){},focus(){},scrollIntoView(){},getContext(){return paint}};}
 const doc={getElementById(id){return elements[id]||=(element(id==='game'||id==='victoryFx'?'canvas':'div'))},createElement:element,querySelectorAll(){return[]},activeElement:{tagName:'BODY'}};
 for(const id of ['overlay','levelLibrary','editor'])doc.getElementById(id).hidden=true;
 const context={Trail:require('./engine'),TrailLevels:require('./levels'),TrailVictory:require('./victory'),document:doc,localStorage:storage,requestAnimationFrame(){},setTimeout(){},Blob,URL,console};context.window=context;context.addEventListener=()=>{};context.matchMedia=()=>({matches:false});vm.createContext(context);vm.runInContext(fs.readFileSync('app.js','utf8'),context);return {run:s=>vm.runInContext(s,context),elements,storage};
}
const app=boot();assert.equal(app.run('activeId'),'builtin-1');app.run('selectLevel(BUILTINS[9])');assert.equal(app.elements.levelTitle.textContent,'Rainbow summit');assert.equal(app.run('game.progress'),0);
app.run('selectLevel(BUILTINS[0]); for(let n=1;n<=6;n++)game.collect({n}); game.p.x=level.flag.x;game.p.y=level.flag.y-20;game.step(1/120,{})');assert.equal(app.run('game.won'),true);assert.equal(app.run('celebration.particles.length'),216);assert.equal(app.run("store.completed.includes('builtin-1')"),true);assert.equal(app.elements.overlay.hidden,true);app.run('for(let t=50;t<=1500;t+=50)frame(t)');assert.equal(app.elements.overlay.hidden,false);assert.equal(app.elements.winLevels.hidden,false);assert.match(app.elements.overlayTitle.textContent,/Every color/);assert.equal((app.elements.sequence.innerHTML.match(/color-step done/g)||[]).length,6);
app.run('restart()');assert.equal(app.run('celebration'),null);assert.equal(app.elements.overlay.hidden,true);assert.equal((app.elements.sequence.innerHTML.match(/color-step done/g)||[]).length,0);
app.run('setMode("edit"); document.getElementById("levelName").value="Saved test"; saveExtra(false)');assert.equal(app.run('store.levels.length'),1);assert.equal(app.elements.levelLibrary.hidden,false);app.run('selectLevel(store.levels[0]);setMode("edit");document.getElementById("levelName").value="Updated test";saveExtra(true)');assert.equal(app.run('store.levels.length'),1);assert.equal(app.run('store.levels[0].name'),'Updated test');assert.equal(app.run('BUILTINS[0].name'),'First colors');const again=boot(app.storage);assert.equal(again.run('store.levels[0].name'),'Updated test');console.log('PASS app skip-level selection, win trigger/overlay/effects, reset, progress states, library save/update/reload, built-in preservation');
