const assert=require('node:assert/strict');const {Game,validate}=require('./engine');const {builtins,LevelStore}=require('./levels');
for(const level of builtins()){
 assert.deepEqual(validate(level),[],level.name);let deaths=0;const g=new Game(level,t=>{if(t==='death')deaths++;});for(let i=0;i<20;i++)g.step(1/120,{});
 for(const target of level.route){
 const support=g.lastBlock;
 if(support&&support.w<=120){const right=target.x>g.p.x+13;const launch=right?support.x+support.w-16:support.x+16;for(let i=0;i<50&&Math.abs(g.p.x+13-launch)>2;i++)g.step(1/120,{right:launch>g.p.x+13,left:launch<g.p.x+13});}
 let landed=false;for(let i=0;i<200;i++){const dx=target.x-(g.p.x+13);g.step(1/120,{right:dx>2,left:dx< -2,jump:i===0});if(g.won){landed=true;break;}if(i>12&&g.p.ground){landed=Math.abs(g.p.y+36-target.y)<2&&Math.abs(g.p.x+13-target.x)<55;break;}}
 assert.ok(landed,`${level.name}: landing ${JSON.stringify(target)}, player ${JSON.stringify(g.p)}`);}
 assert.equal(deaths,0,level.name);assert.equal(g.progress,6,level.name);assert.equal(g.won,true,level.name);console.log('PASS',level.id,level.name);
}
const storage={value:null,getItem(){return this.value},setItem(k,v){this.value=v}};const store=new LevelStore(storage);const a=store.save(builtins()[0],'My first level');const b=store.save(builtins()[1],'My second level');assert.equal(store.levels.length,2);store.complete(a.id);assert.ok(store.completed.includes(a.id));store.save({...a,spawn:{x:40,y:520}},'Renamed',a.id);assert.equal(store.levels.length,2);assert.ok(!store.completed.includes(a.id));const loaded=new LevelStore(storage);assert.equal(loaded.levels[0].name,'Renamed');assert.equal(loaded.levels[1].id,b.id);assert.throws(()=>loaded.save({...a,blocks:[]},'Bad'));assert.throws(()=>loaded.save(a,'  '));const before=JSON.stringify(loaded.levels);storage.setItem=()=>{throw Error('Quota exceeded')};assert.throws(()=>loaded.save(a,'Fail'));assert.equal(JSON.stringify(loaded.levels),before);console.log('PASS library save, independent levels, update, reload, validation, storage failure rollback');
const Victory=require('./victory');const fx=Victory.create(700,300);assert.equal(fx.particles.length,216);assert.equal(new Set(fx.particles.map(p=>p.color)).size,6);let arcs=0,paint=0;const fake={clearRect(){},save(){},restore(){},beginPath(){},arc(){arcs++},stroke(){},translate(){},rotate(){},fillRect(){paint++}};Victory.draw(fake,fx,.3);assert.equal(arcs,6);assert.ok(paint>0);const reduced=Victory.create(700,300,true);paint=0;Victory.draw(fake,reduced,.3);assert.equal(paint,0);console.log('PASS rainbow explosion drawing and reduced motion');
