const assert=require('node:assert/strict');const {Game,validate}=require('./engine');const {builtins,LevelStore}=require('./levels');
function followRoute(level,route=level.route){
 assert.deepEqual(validate(level),[],level.name);let deaths=0;const orders=[];const g=new Game(level,(t,n,expected)=>{if(t==='death')deaths++;if(t==='order')orders.push([n,expected]);});for(let i=0;i<20;i++)g.step(1/120,{});
 for(const target of route){
 if(target.walk){for(let i=0;i<500&&!g.won&&Math.abs(g.p.x+13-target.x)>2;i++){const dx=target.x-(g.p.x+13);g.step(1/120,{right:dx>2,left:dx< -2});}assert.ok(g.won||Math.abs(g.p.x+13-target.x)<=3,`${level.name}: walking ${JSON.stringify(target)}, player ${JSON.stringify(g.p)}`);continue;}
 const support=g.lastBlock;
 if(support&&support.w<=120){const right=target.x>g.p.x+13;const launch=right?support.x+support.w-16:support.x+16;for(let i=0;i<50&&Math.abs(g.p.x+13-launch)>2;i++)g.step(1/120,{right:launch>g.p.x+13,left:launch<g.p.x+13});}
 let landed=false;for(let i=0;i<200;i++){const dx=target.x-(g.p.x+13);g.step(1/120,{right:dx>2,left:dx< -2,jump:i===0});if(g.won){landed=true;break;}if(i>12&&g.p.ground){landed=Math.abs(g.p.y+36-target.y)<2&&Math.abs(g.p.x+13-target.x)<55;break;}}
 assert.ok(landed,`${level.name}: landing ${JSON.stringify(target)}, player ${JSON.stringify(g.p)}`);}
 assert.equal(deaths,0,level.name);return {g,orders};
}
for(const level of builtins()){const {g,orders}=followRoute(level);assert.deepEqual(orders,[],level.name+' no accidental resets');assert.equal(g.progress,6,level.name);assert.equal(g.won,true,level.name);assert.equal(g.result,'perfect',level.name);console.log('PASS',level.id,level.name);}
const mirror=builtins().at(-1),mirrorReverse=followRoute(mirror,mirror.reverseRoute);assert.equal(mirrorReverse.g.result,'perfect');assert.equal(mirrorReverse.g.direction,-1);assert.deepEqual(mirrorReverse.orders,[]);console.log('PASS mirror circuit physical reverse route');
const reverseTrail=builtins()[0];reverseTrail.allowReverse=true;reverseTrail.blocks=reverseTrail.blocks.map(b=>({...b,n:b.n?7-b.n:0}));const reverseRun=followRoute(reverseTrail);assert.equal(reverseRun.g.result,'perfect');assert.equal(reverseRun.g.direction,-1);assert.deepEqual(reverseRun.orders,[]);console.log('PASS full physical reverse trail');
const lesson=builtins()[2];const mistake=followRoute(lesson,[lesson.route[0],lesson.route[1],lesson.route[4]]);assert.equal(mistake.g.progress,0);assert.deepEqual(mistake.orders,[[3,2]],'forward shortcut teaches yellow is wrong before orange');assert.equal(mistake.g.won,false);console.log('PASS teaching shortcut resets progress without death');
const storage={value:null,getItem(){return this.value},setItem(k,v){this.value=v}};const store=new LevelStore(storage);const a=store.save(builtins()[0],'My first level');const b=store.save(builtins()[1],'My second level');assert.equal(store.levels.length,2);assert.equal(a.lesson,undefined,'custom levels do not inherit curated hints');store.complete(a.id);assert.ok(store.completed.includes(a.id));store.save({...a,spawn:{x:40,y:520}},'Renamed',a.id);assert.equal(store.levels.length,2);assert.ok(!store.completed.includes(a.id));const loaded=new LevelStore(storage);assert.equal(loaded.levels[0].name,'Renamed');assert.equal(loaded.levels[1].id,b.id);assert.throws(()=>loaded.save({...a,blocks:[]},'Bad'));assert.throws(()=>loaded.save(a,'  '));const before=JSON.stringify(loaded.levels);storage.setItem=()=>{throw Error('Quota exceeded')};assert.throws(()=>loaded.save(a,'Fail'));assert.equal(JSON.stringify(loaded.levels),before);console.log('PASS library save, independent levels, update, reload, validation, storage failure rollback');
const {RatingStore}=require('./levels');const ratingStorage={data:{},getItem(k){return this.data[k]||null},setItem(k,v){this.data[k]=v}};const ratings=new RatingStore(ratingStorage);ratings.set('builtin-11','good');assert.equal(ratings.get('builtin-11'),'good');ratings.set('builtin-11','okay');assert.equal(new RatingStore(ratingStorage).get('builtin-11'),'okay');ratings.clear('builtin-11');assert.equal(ratings.get('builtin-11'),'');ratings.set('builtin-11','okay');assert.throws(()=>ratings.set('builtin-11','great'));const savedRatings=JSON.stringify(ratings.ratings);ratingStorage.setItem=()=>{throw Error('quota')};assert.throws(()=>ratings.set('builtin-12','bad'));assert.equal(JSON.stringify(ratings.ratings),savedRatings);console.log('PASS rating validation, update, clear, reload and storage failure rollback');
const Victory=require('./victory');const fx=Victory.create(700,300);assert.equal(fx.particles.length,216);assert.equal(new Set(fx.particles.map(p=>p.color)).size,6);let arcs=0,paint=0;const fake={clearRect(){},save(){},restore(){},beginPath(){},arc(){arcs++},stroke(){},translate(){},rotate(){},fillRect(){paint++}};Victory.draw(fake,fx,.3);assert.equal(arcs,6);assert.ok(paint>0);const reduced=Victory.create(700,300,true);paint=0;Victory.draw(fake,reduced,.3);assert.equal(paint,0);console.log('PASS rainbow explosion drawing and reduced motion');
