const assert=require('node:assert/strict');const {create,NOTES}=require('./audio');const {Game,starter}=require('./engine');
function fake(){const notes=[],voices=[];let resumes=0;const ctx={state:'suspended',currentTime:0,destination:{},resume(){resumes++;this.state='running';return Promise.resolve();},createOscillator(){const o={frequency:{setValueAtTime(f){notes.push(f);}},connect(){},disconnect(){},start(){},stops:[],stop(t){this.stops.push(t);}};voices.push(o);return o;},createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}},connect(){},disconnect(){}};}};return {ctx,notes,voices,get resumes(){return resumes;}};}
(async()=>{
const f=fake();let factories=0;const sound=create({makeContext:()=>{factories++;return f.ctx;}});sound.start();sound.start();assert.equal(factories,0,'no context before interaction');assert.equal(f.notes.length,0);assert.equal(await sound.unlock(),true);assert.equal(f.notes.length,2,'one pending opening note plus overtone');assert.equal(f.notes[0],NOTES[0]);await sound.unlock();assert.equal(f.notes.length,2,'further interactions do not replay start');
for(let i=1;i<=7;i++)sound.note(i);assert.deepEqual(f.notes.filter((_,i)=>i%2===0),NOTES);assert.ok(Math.abs(NOTES[7]/NOTES[0]-2)<1e-7,'winning note is an octave up');assert.equal(f.voices.at(-1).stops[0],.87,'longer victory release');
sound.setEnabled(false);assert.ok(f.voices.every(v=>v.stops.length===2),'mute cancels sounding voices');const count=f.notes.length;sound.start();sound.note(3);await sound.unlock();assert.equal(f.notes.length,count,'mute remains silent');sound.setEnabled(true);await sound.unlock();assert.equal(f.notes.length,count,'no stale sounds replay after unmuting');sound.start();assert.equal(f.notes.at(-2),NOTES[0]);
const delayed=fake();let release;delayed.ctx.resume=()=>new Promise(resolve=>{release=()=>{delayed.ctx.state='running';resolve();};});const waiting=create({makeContext:()=>delayed.ctx});waiting.start();const unlocking=waiting.unlock();waiting.setEnabled(false);release();await unlocking;assert.equal(delayed.notes.length,0,'mute during resume cancels pending start');
const blocked=create({makeContext:()=>{throw Error('unavailable');}});blocked.start();assert.equal(await blocked.unlock(),false,'unavailable audio does not break gameplay');
const flow=fake(),music=create({makeContext:()=>flow.ctx});await music.unlock();const g=new Game(starter(),(type,n)=>{if(type==='reset'||type==='order')music.start();if(type==='color')music.note(n);if(type==='win')music.note(7);});for(let n=1;n<=6;n++){g.collect({n});g.collect({n});}g.p.x=g.level.flag.x;g.p.y=g.level.flag.y-20;g.step(1/120,{});assert.equal(g.won,true);assert.deepEqual(flow.notes.filter((_,i)=>i%2===0),NOTES,'real game has one note per newly collected color');g.reset();g.collect({n:1});g.collect({n:3});assert.equal(flow.notes.at(-2),NOTES[0],'wrong sequence returns to do');
console.log('PASS C-major mapping, octave victory, gesture unlock, single queued start, repeat suppression, mute/cancellation, blocked audio, real engine sound sequence');
})().catch(error=>{console.error(error);process.exitCode=1;});
